import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Region;

/**
 * Generated by Copilot on 11/17/2025
 * I added text member and getter/setters
 */
public class CategoryButton extends HBox {
	private String text;
	private Button parentButton;
	
    public CategoryButton(String text, Button parentButton) {
        // Kill button
        Button killBtn = new Button("✖");
        killBtn.setFocusTraversable(false);
        killBtn.setStyle("-fx-background-color: transparent; -fx-text-fill: red; -fx-font-weight: bold;");
        
        
        // Label with category text
        Label label = new Label(text);
        label.setStyle("-fx-padding: 0 5 0 5;");
        setText(text);
        setParentButton(parentButton);

        // Layout
        this.getChildren().addAll(killBtn, label);
        this.setStyle("-fx-background-color: #e0e0e0; -fx-border-color: #999; -fx-border-radius: 4; -fx-padding: 3 6 3 6; -fx-spacing: 4; -fx-alignment: center-left;");
        this.setMinHeight(Region.USE_PREF_SIZE);

        // Kill behavior
        killBtn.setOnAction(e -> {
            if (this.getParent() instanceof javafx.scene.layout.Pane parent) {
            	getParentButton().setVisible(true);
                parent.getChildren().remove(this);
                
            }
        });
    }

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Button getParentButton() {
		return parentButton;
	}

	public void setParentButton(Button parentButton) {
		this.parentButton = parentButton;
	}
    
    
    
    
}